# Generated by Django 5.2 on 2025-04-24 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changingApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateUser',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='image_url',
        ),
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Категория товара'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='condition',
            field=models.CharField(choices=[('new', 'Новый'), ('used', 'Б/У')], max_length=10, verbose_name='Состояние товара'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.TextField(verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
